language: python
python:
  - "3.6"
install:
  - "pip install pipenv"
  - "pip install coveralls"
  - "pipenv install"
script:
  coverage run manage.py test
after_success:
  coveralls
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
env:
  global:
    - DJANGO_DB=travis_ci_test
    - DJANGO_DB_USER=postgres
    - DJANGO_SETTINGS_MODULE=hamlet.settings.test
