language: python
python:
- '3.6'
install:
- pip install pipenv
- pip install coveralls
- pipenv install
script: coverage run manage.py test
after_success: coveralls
addons:
  postgresql: "9.6"
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
env:
  global:
  - DJANGO_DB=travis_ci_test
  - DJANGO_DB_USER=postgres
  - DJANGO_SETTINGS_MODULE=hamlet.settings.test
before_deploy:
  - rm -rf hamlet/testmodels/
  - pipenv run pip freeze > requirements.txt
  #- pipenv lock --requirements > requirements.txt # broken as of 2/23/2018
  - git add requirements.txt
  - git commit -am "requirements/testmodels cleanup"
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAJKJRORTATM44CW4A
  secret_access_key: # This is encrypted, so it's OK to have it here.
    secure: "XR2aig74nIUGMr6qwgK+yTFH+btwdO5E5y8UO5zWX7DLTfTIpQm61GjWrmhlNNS+NiL6+eZ2NSuccsHC7pccq3oM6jry5phkxQdo8e7HPkkpHnc/Nl3s/w693dFmtMJTQi1uoaP2+qZI7u4rj1m5sAzfct8VVTYwIxMosw+PVTOpawmlLgQPDNEoQ1D8m3F9waS6v/kzQuARXfV6mRzXUBYY7nlGVNboeYbDzeuUhKC18+m0ZwS3VkJEZ76TxmCtqILA4VtWC3O5UgzGkBI8DbALuU9acAhjCOfB09YmQxsyk+cww6rXbKekedrkd9QeDz6+YZ8dMK1O11xItIKpmUNONsX6sArpr81Qa76mx4Q+ctBVTQeJ+zoCjmzPs4C2QSgR68Fo6kF+Tmn2oyT44UsljhYXDQx96L4iOA65XpG62hKXqZ0idCXgkgGa0JxWWKjivp1wGKvrM9SMGiGm3droqZwb9tfNoQnATCxOgrCPhJTN9ZN1xrtB+YWKN7HtLUqXQdl24kbUOu8jGemt1yjDVQfD45vX5n1r1bMjI7JOYuqAhtOBZuxX/m4iNExE9aRDvDQ+56sHwcg3BhpypG+8pto1/+h3KqiTd+rISn3tf5g6k8AXPDl9WYSt+YTCGUQHMZiT1AvbPnpEJXqTrsA8An7p0anAs5AxaBOz3S4="
  region: us-east-2
  bucket_name: elasticbeanstalk-us-east-2-214921548711
  bucket_path: hamlet
  app: hamlet
  env: Hamlet-env #change to Hamlet-prod to deploy to prod
  skip_cleanup: true
  on:
    repo: thatandromeda/hamlet
    branch: master
