language: python
python:
  - "3.6"
install:
  - "pip install pipenv"
  - "pip install coveralls"
  - "pipenv install --dev"
script:
  pipenv coverage run --source=hamlet manage.py test
after_success:
  coveralls
